<?php
// This file is part of MuTMS suite of plugins for Moodle™ LMS.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// phpcs:disable moodle.Files.BoilerplateComment.CommentEndedTooSoon

namespace auth_musaml\local;

use OpenSSLAsymmetricKey;

/**
 * Thin wrappers around the PHP openssl extension for SP key and certificate handling.
 *
 * All methods work on PEM strings and key handles only, nothing here touches
 * the database or global configuration.
 *
 * @package    auth_musaml
 * @copyright  2026 Petr Skoda
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
final class openssl {
    /** @var int default RSA key size */
    public const KEY_BITS = 2048;

    /** @var int default certificate validity in days */
    public const CERT_DAYS = 3650;

    /** @var string default signature digest */
    public const DIGEST = 'sha256';

    /**
     * Minimal openssl configuration, written into the request directory when needed.
     *
     * Without it the distribution defaults, such as C=AU and ST=Some-State, end up in the
     * certificate subject. Only certificate generation needs it, and the file is gone at
     * the end of the request.
     *
     * @return string path of the configuration file
     */
    public static function get_config_path(): string {
        static $file = null;

        if ($file === null || !file_exists($file)) {
            $config = "# Generated by auth_musaml, keeps system defaults out of certificate subjects.\n"
                . "[ req ]\ndistinguished_name = req_distinguished_name\nprompt = no\n\n"
                . "[ req_distinguished_name ]\n";
            $file = make_request_directory() . '/openssl.cnf';
            file_put_contents($file, $config);
        }
        return $file;
    }

    /**
     * Generate a new RSA private key.
     *
     * @param int $bits
     * @return OpenSSLAsymmetricKey
     */
    public static function generate_key(int $bits = self::KEY_BITS): OpenSSLAsymmetricKey {
        $key = openssl_pkey_new([
            'config' => self::get_config_path(),
            'private_key_type' => OPENSSL_KEYTYPE_RSA,
            'private_key_bits' => $bits,
            'digest_alg' => self::DIGEST,
        ]);
        if (!$key) {
            throw new \RuntimeException('Cannot generate private key: ' . self::last_error());
        }
        return $key;
    }

    /**
     * Create a self-signed X.509 certificate for the given key.
     *
     * @param OpenSSLAsymmetricKey $key
     * @param array $dn distinguished name fields, such as commonName and organizationName
     * @param int $days
     * @param string $digest
     * @return string certificate in PEM format
     */
    public static function create_self_signed_cert(
        OpenSSLAsymmetricKey $key,
        array $dn,
        int $days = self::CERT_DAYS,
        string $digest = self::DIGEST,
    ): string {
        $options = ['config' => self::get_config_path(), 'digest_alg' => $digest];
        $csr = openssl_csr_new($dn, $key, $options);
        if (!$csr) {
            throw new \RuntimeException('Cannot create certificate request: ' . self::last_error());
        }
        $serial = random_int(1, PHP_INT_MAX);
        $x509 = openssl_csr_sign($csr, null, $key, $days, $options, $serial);
        if (!$x509) {
            throw new \RuntimeException('Cannot sign certificate: ' . self::last_error());
        }
        $pem = '';
        if (!openssl_x509_export($x509, $pem)) {
            throw new \RuntimeException('Cannot export certificate: ' . self::last_error());
        }
        return $pem;
    }

    /**
     * Export private key as encrypted PEM.
     *
     * @param OpenSSLAsymmetricKey $key
     * @param string $passphrase
     * @return string
     */
    public static function export_key(OpenSSLAsymmetricKey $key, string $passphrase): string {
        if ($passphrase === '') {
            throw new \InvalidArgumentException('Private key passphrase must not be empty');
        }
        $pem = '';
        $options = ['config' => self::get_config_path(), 'encrypt_key_cipher' => OPENSSL_CIPHER_AES_256_CBC];
        if (!openssl_pkey_export($key, $pem, $passphrase, $options)) {
            throw new \RuntimeException('Cannot export private key: ' . self::last_error());
        }
        return $pem;
    }

    /**
     * Load an encrypted PEM private key.
     *
     * @param string $pem
     * @param string $passphrase
     * @return OpenSSLAsymmetricKey|null null if the key or passphrase is invalid
     */
    public static function load_key(string $pem, string $passphrase): ?OpenSSLAsymmetricKey {
        $key = openssl_pkey_get_private($pem, $passphrase);
        return $key ?: null;
    }

    /**
     * Export private key as unencrypted PEM, needed by php-saml which does not support passphrases.
     *
     * @param OpenSSLAsymmetricKey $key
     * @return string
     */
    public static function export_key_plain(OpenSSLAsymmetricKey $key): string {
        // No configuration needed here, exporting an existing key reads no defaults.
        $pem = '';
        if (!openssl_pkey_export($key, $pem)) {
            throw new \RuntimeException('Cannot export private key: ' . self::last_error());
        }
        return $pem;
    }

    /**
     * Does the certificate belong to the private key?
     *
     * @param string $certpem
     * @param OpenSSLAsymmetricKey $key
     * @return bool
     */
    public static function key_matches_cert(string $certpem, OpenSSLAsymmetricKey $key): bool {
        return openssl_x509_check_private_key($certpem, $key);
    }

    /**
     * Parse certificate details.
     *
     * @param string $pem
     * @return array|null keys: subject, issuer, serial, notbefore, notafter, fingerprint; null if not a certificate
     */
    public static function parse_cert(string $pem): ?array {
        $info = openssl_x509_parse($pem);
        if (!$info) {
            return null;
        }
        return [
            'subject' => self::format_dn($info['subject'] ?? []),
            'issuer' => self::format_dn($info['issuer'] ?? []),
            'serial' => (string)($info['serialNumberHex'] ?? $info['serialNumber'] ?? ''),
            'notbefore' => (int)($info['validFrom_time_t'] ?? 0),
            'notafter' => (int)($info['validTo_time_t'] ?? 0),
            'fingerprint' => self::fingerprint($pem),
        ];
    }

    /**
     * Certificate fingerprint as colon separated upper case hex.
     *
     * @param string $pem
     * @param string $algorithm
     * @return string|null
     */
    public static function fingerprint(string $pem, string $algorithm = 'sha256'): ?string {
        // Parsing first avoids the PHP warning that openssl_x509_read() emits for non-certificates.
        if (!openssl_x509_parse($pem)) {
            return null;
        }
        $raw = openssl_x509_fingerprint($pem, $algorithm);
        if ($raw === false) {
            return null;
        }
        return implode(':', str_split(strtoupper($raw), 2));
    }

    /**
     * Strip PEM armour and whitespace, returns bare base64 as used inside SAML XML.
     *
     * @param string $pem
     * @return string
     */
    public static function strip_pem(string $pem): string {
        $pem = preg_replace('/-----[A-Z ]+-----/', '', $pem);
        return preg_replace('/\s+/', '', $pem);
    }

    /**
     * Render DN array as one line.
     *
     * @param array $dn
     * @return string
     */
    private static function format_dn(array $dn): string {
        $parts = [];
        foreach ($dn as $k => $v) {
            if (is_array($v)) {
                $v = implode('+', $v);
            }
            $parts[] = $k . '=' . $v;
        }
        return implode(', ', $parts);
    }

    /**
     * Collect pending openssl error messages.
     *
     * @return string
     */
    private static function last_error(): string {
        $errors = [];
        while ($error = openssl_error_string()) {
            $errors[] = $error;
        }
        return implode('; ', $errors);
    }
}
